### ISSUE TITLE
Request: saving to other filetypes

### ISSUE THREAD

**Issue by 1nterject** [rytsikau/ee.Yrewind#1]
MP4s can become corrupted if FFMPEG crashed. I think it would be nice if we can save to more resilient filetypes such as `.mkv`, `.ts`, or `.avi`.

**Comment by rytsikau** [comment]
If the broadcast was interrupted or a network error occurred, the mp4 output file is indeed corrupted (due to moov atom error). Next release will add output format selection

**Comment by rytsikau** [comment]
Hello! The new release has the ability to choose the format for saving. Try TS ('-vformat = ts') - it seems it work correctly on network errors and FFmpeg crashes
