### ISSUE TITLE
ERROR 9211: Cannot get ID information 

### ISSUE THREAD

**Issue by sideloading** [rytsikau/ee.Yrewind#10]
Title, am getting that error message when trying to download a livestream using the latest version 21.015.

```
yrewind -url=https://www.youtube.com/watch?v=XXXX-start=beginning
--> ee.Yrewind (started at 3/02/2021 8:56:31 PM)
getting live stream data...
--> ERROR 9211: Cannot get ID information (3/02/2021 8:57:00 PM)
```

Using 20.113 it gets the correct information, ~~but I cannot use the -start parameter to download from the beginning~~. I was able to download the livestream by adjusting the -start parameter. 

Windows 10 2004
Chrome 88.0.4324.146 (Official Build) (64-bit)

**Comment by rytsikau** [comment]
Hello!
It could be a syntax error in the command line, it could be a copyrighted stream, or it could be a program error. Without knowing what stream we are talking about, it's hard to say for sure
