### ISSUE TITLE
unable to verify the saved video file is correct

### ISSUE THREAD

**Issue by ghost** [rytsikau/ee.Yrewind#11]
Hi,
at first I want to thank you for your work. Finally we're able again to download live streams as any other tool is broken...

I've used yrewind on very long 180 hour stream and download it in 5 hour chunks (36 parts total).
On some of the chunks I got the message: "unable to verify the saved video file is correct". Tried it several time, but I get always this message on the same parts. 

What does this mean? Is the file corrupt or something else? Why does this habben always on the same parts but others are fine?

Here an example stream: https://www.youtube.com/watch?v=vJiXOtDbzG0
The first 5 hours get exacly the message above, the following 5 hours are fine.
(btw. I'm not shure how long this stream will be online)

**Comment by rytsikau** [comment]
Hello!

This message appears if the FFmpeg process terminated with an error, or the video duration could not be checked (broken file), or the video duration does not match the requested one.

If the file is not broken, and the duration is in order, it's possible there is an audio and video desynchronization at some point in the file. Try to download it by splitting into several segments.

Also, desync often occurs at the very beginning of stream, when streamer is probably making some kind of settings.

**Comment by ghost** [comment]
Ok, I think youtube is somehow messing around with the stream.

I've downloaded today a part with same start point as yesterday but the stream was shifted for serveral minutes. The earliest possible startpoint has also changed since yesterday but only for some seconds...
