### ISSUE TITLE
How to download a broadcast for more than 1 hour

### ISSUE THREAD

**Issue by browjob** [rytsikau/ee.Yrewind#12]
How to download a broadcast for more than 1 hour? For example, the broadcast lasts 7 hours, I need to download all 7 hours and if the broadcast continues to download until it ends.

**Comment by rytsikau** [comment]
You can repeat a line like "yrewind -url=https://www.youtube.com/watch?v=9Auq9mYxFEE" several times in a batch file.
Or explicitly specify the "-duration" parameter. See readme file
