### ISSUE TITLE
Detected Trojan in the downloaded file

### ISSUE THREAD

**Issue by Grenlet** [rytsikau/ee.Yrewind#13]
The program was working fine but I encountered something weird recently. My antivirus detected a "Trojan:Win32/Wacatac.D2!ml" in the downloaded zip folder. Could you take a look at this issue? Thanks.

**Comment by rytsikau** [comment]
It is a false positive of MS Defender's heuristic engine. I wrote to Microsoft, hope they fix it quickly )

**Comment by Grenlet** [comment]
Thanks for letting me know about this!
