### ISSUE TITLE
Virustotal warnings version 21.022

### ISSUE THREAD

**Issue by sed03** [rytsikau/ee.Yrewind#14]
Please check latest version 21.022, probably false positives but it doesn't look good:

9 engines detected this file
https://www.virustotal.com/gui/file/f6b859e6129e8bb9d8343320ac299549b601c3ed6f01841cde8b8953759cf1e8/detection

**Comment by rytsikau** [comment]
Yes, I see. I wrote to two of them about false positives. I think most use the same engine

**Comment by rytsikau** [comment]
After yesterday's appeal, now only 3 out of 70 antiviruses consider the file suspicious - McAfee, Qihoo-360 and Sangfor. Perhaps they consider any unsigned file to be suspicious? One way or another, McAfee technical support is not responding, and to contact Qihoo-360 and Sangfor you need to register on their website. I think it's better to put up with :)

**Comment by sed03** [comment]
3 out 70 is okey. Several downloads has 1-5 warnings.

/Stefan


Den tors 25 feb. 2021 11:29Eugen Rytikov <notifications@github.com> skrev:
