### ISSUE TITLE
Huge thanks and feature request audio only

### ISSUE THREAD

**Issue by computerfreak105** [rytsikau/ee.Yrewind#15]
This is really awesome, can't thank you enough. You managed something ytdl and streamlink can't do. It's exactly what I was looking for. And thanks for providing all the examples in the documentation. If you give me your PayPal you get something.
Because I'm blind I don't really need the videos. I convert them to audio afterwards anyway. So, if it would be an easy thing to do to just get the m4a audio (I think it's format 140), that would be awesome and might speed up downloads before the real time downloading happens. Thanks for considering and cheers!

**Comment by rytsikau** [comment]
Hello!

Thanks for the kind words! My Paypal is the same as my email, but in my country Paypal only works with outgoing payments, incoming is not possible. Probably hard to believe, but it is. The only way I know to transfer money is with Payoneer, but it's more complicated.

The ability to only save audio is a reasonable option. Maybe in the next release I'll implement it. Until then, try downloading the video at the lowest resolution ("-r=144" or, more simply "-r=1"). The file size is almost the same as that of pure audio!

**Comment by computerfreak105** [comment]
Curious, what country is this without incoming Paypal? … I’ll have a look at Payoneer then if I can manage it, never heard of it though.
Thanks for the idea of the lower video resolution. I hope the audio quality will still be the same.
All the best.

**Comment by rytsikau** [comment]
This is the very center of Europe - Belarus :)
To receive payment, I need to know your email, name and country (can be sent to my email).
With this, I can create a Payoneer payment request, that will be sent to your email. It contains a link button to standard payment page.

**Comment by rytsikau** [comment]
New feature is available now, see the new version! Supported audio formats - aac, m4a and wma
