### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by computerfreak105** [rytsikau/ee.Yrewind#16]
It seems that youtube changed something, or I'm doing it wrong?
Yesterday a few streams went online and the program didn't catch them. And now I can't download anymore. My syntax is:

yrewind -url=https://www.youtube.com/watch?v=21X5lGlDOfg -start=beginning -duration=300 -output=*start*.ts -r=1
Also tried with: https://www.youtube.com/watch?v=K1l0rbRdEdQ
These don't work right now.

And I noticed that some streams won't be downloaded when I add *title* into the -output syntax. Par example when waiting for live streams with this channel:
yrewind -url=https://www.youtube.com/channel/UCoVt8Q93OmQx1Tz8ovhHjow -start=wait -output=*start *title*.ts -duration=300 -r=1

Thanks for a fix or for correcting my syntax if I missed something.

**Comment by rytsikau** [comment]
These streams contain characters in their titles that are incompatible with the filesystem (colon, pipe, etc.). This is my omission, this check has apparently been lost from some version. I'll fix it in the next release. For now, just don't use the `*title*` mask when saving - both streams you specified are saved perfectly.

**Comment by computerfreak105** [comment]
Curious, now these urls are working again. Let’s hope it stays this way.
Thanks for giving it a try and for the *title* fix later.

**Comment by rytsikau** [comment]
fixed

**Comment by computerfreak105** [comment]
Thanks, works great!
