### ISSUE TITLE
Stuck on Caching Data

### ISSUE THREAD

**Issue by idx-ctrl** [rytsikau/ee.Yrewind#18]
Hey, no matter what link or format i put in the console (even your examples) it will always get stuck on "caching data, wait 1 Minute" and does not save any file. and then after 1 minute it just closes itself and i dont find any output in the saved streams folder (its just empty). the duration doesen't matter (1 Minute or default does not change anything).

Windows 10 Pro 64 bit Build 19042
![error](https://user-images.githubusercontent.com/82401641/114443396-ee16ba80-9bcd-11eb-95f6-1f7e2c8fbb20.JPG)

**Comment by idx-ctrl** [comment]
It does only work if I put the start command! for example:

yrewind -url='https://www.youtube.com/watch?v=9Auq9mYxFEE' **does nothing**
yrewind -url='https://www.youtube.com/watch?v=9Auq9mYxFEE' -start=beginning **works**

**Comment by rytsikau** [comment]
With the first line, the program first waits for 1 minute, then starts recording in real time, i.e. slow. Check, possibly there are already files in the folder of recorded streams

**Comment by idx-ctrl** [comment]
> With the first line, the program first waits for 1 minute, then starts recording in real time, i.e. slow. Check, possibly there are already files in the folder of recorded streams

There is no file and it just closes after half a minute, as i said

**Comment by rytsikau** [comment]
After a minute, does anything appear in the console? Error, or countdown timer, or something else

**Comment by idx-ctrl** [comment]
See

Am 12.04.2021 19:37 schrieb Yauheni Rytsikau:

**Comment by computerfreak105** [comment]
I’d like to give it a try on my system, Win 10 Pro.
What is the exact syntax (including wait parameter) which doesn’t work for you?

**Comment by idx-ctrl** [comment]
yrewind -url=https://www.youtube.com/watch?v=9Auq9mYxFEE
pause

Am 12.04.2021 19:57 schrieb computerfreak105:

**Comment by computerfreak105** [comment]
Indeed, it’s not working either for me. The url is playing fine in the browser but downloading doesn’t work. There is no other file in the download destination. I think there is really something not working here. Might perhaps explain my download failure in my own post.

**Comment by idx-ctrl** [comment]
I updated the picture with an error code in the start post

**Comment by rytsikau** [comment]
Can you check the same with the previous version?

I have no idea, for me all works as usual

**Comment by computerfreak105** [comment]
Tried it with 21.041, 21.031 and 21.023 . None of them are working with this url.

**Comment by rytsikau** [comment]
Accidentally discovered the same thing with a stream https://www.youtube.com/watch?v=eJ7ZkQ5TC08
At least very similar to what you are describing. In this case, the problem is in the YouTube API - incorrect UTC time in the HLS manifest

**Comment by computerfreak105** [comment]
Thanks, I can confirm it doesn’t work on my system as well.

**Comment by rytsikau** [comment]
(reported to YouTube team)
