### ISSUE TITLE
Source code is meaningless, and doesn't compile

### ISSUE THREAD

**Issue by jimklo** [rytsikau/ee.Yrewind#19]
So it concerns me that you have something that looks like source code, however it's ain't jack, and then while it looks active you've made nothing but minor robotic changes to the README.txt... Then you're providing some black box obfuscated assembly.

WTH is this doing? Something nefarious? It seems the meat of the source code for this tool is missing and you're hiding it for some reason. Basically all you've uploaded is some C# wrapper that constructs some FFMpeg arguments - using algorithms that don't exist in the actual assembly.

**Comment by rytsikau** [comment]
Hi!

The published part of the source code reflects the main algorithm - indeed, the stream is downloaded using FFmpeg, and you can see the command line that is passed to FFmpeg. I do not publish the entire source code for a simple reason - I hope to sell it. I think this tool has value, for example, for those who work with news.

I assure you, there is nothing in the program that is not described in the readme (well, except for the test mode). You can run a network sniffer and make sure the program is only accessing the Github and YouTube servers.

Also, before publishing the first release (in the summer of 2020), I contacted the Google security service, describing in detail my algorithm for downloading live streams and the possibilities it provides. Their answer was - it's not "severe enough for us to track it a security bug".

Of course, there is still a legal aspect. Here I can only say that Yrewind does NOT download copyrighted live streams. In any case, Yrewind does the same thing as any browser - it presents in a convenient form information that is publicly available on the Internet.
