### ISSUE TITLE
What is the proper way to setup proxy for it?

### ISSUE THREAD

**Issue by Explorare** [rytsikau/ee.Yrewind#2]
I've tried specify proxy for `yrewind.exe` `chrome.exe` and `ffmpeg.exe` using Proxifier but with no luck. The program can load the metadata but the FFmpeg received nothing. The program will keep "saving" without any actual file. No network or disk activity. 

And there is a error message when the program stops.
`--> ERROR 9411: Cannot process live stream with FFmpeg library (12/30/2020 4:03:55 PM)`

Thanks

**Comment by rytsikau** [comment]
Hi! Try to enable the "Localhost" rule (if disabled). Maybe the reason is the exchange of data between Yrewind and FFmpeg

**Comment by Explorare** [comment]
You are right. I did apply proxy rules for all traffic which cause the issue. Use the minimal rules as following fixes the issue. 
`*.googlevideo.com; *.doubleclick.net; *.gstatic.com; *.googleapis.com;`
Works like a charm. Thanks.

**Comment by Explorare** [comment]
The program broke for me after `v20.124`. The error message shown as follow:
`ERROR 9411: Cannot process live stream with FFmpeg library (1/4/2021 12:19:00 AM)`

The proxy config in Proxifier is this:
![image](https://user-images.githubusercontent.com/5090766/103483618-6e858c80-4e23-11eb-8d20-fc50b7f9d1de.png)

It worked for `v20.123`. I've tried disable this specific rule and route the global traffic through that local proxy and the program works again. I think Proxifier tried to hook the ffmpeg which make yrewind failed to load ffmpeg?

Would you like to spend some effort to fix this or add a built in http (or socks) proxy option? Thanks for your effort and happy new year. 🎉

**Comment by rytsikau** [comment]
Yrewind communicates with FFmpeg on port 7799 (no internet, only localhost). Both require an Internet connection, the usual port 443. Also, starting with version 20.124, the dependency on Google Chrome has been removed. Maybe this is the reason?

**Comment by Explorare** [comment]
Thanks for the details, I used the new rules that proxy all `443` port traffic from `yrewind.exe` and `ffmpeg.exe` and bypass all `7799` port for them, and it works like a charm. 🎉

**Comment by Explorare** [comment]
Sorry for reopening this issue again because I met the similar issue again and didn't find a solution for hours.

The output kept saying "ERROR 9210: Cannot download ID information" or "ERROR 9043: Unable to check for updates" no matter what proxy methods I used.

1. Set the global proxy in system settings and the program ignored it, didn't see any related connection in proxy server.
2. Using Proxifier to catch the connection from `yrewind.exe` and `ffmpeg.exe` but failed. 
3. Using Proxifier to catch any connection from terminal, the curl works but not for yrewind.
4. Using proxychains but failed with following output:

```
$ proxychains .\yrewind.exe -url=Y-jJ7I5NJWQ
[PID10224] [I] 2021/05/20 08:54:12 <> localhost:12450
[PID10224] [I] 2021/05/20 08:54:12 Ws2_32.dll connect(1296 224.31.163.166:443 16) -> raw.githubusercontent.com:443 PROXY
--> ee.Yrewind (started at 5/20/2021 8:54:12 AM)
getting live stream data...[PID10224] [I] 2021/05/20 08:54:14 <> localhost:12450
[PID10224] [I] 2021/05/20 08:54:14 Ws2_32.dll connect(1604 224.76.172.4:443 16) -> www.youtube.com:443 PROXY
--> ERROR 9210: Cannot download ID information (5/20/2021 8:54:40 AM)
[I] 2021/05/20 08:54:40 All Windows descendant process exited.
[I] 2021/05/20 08:54:40 Master exiting
```

This really makes me sad. I have failed to record interesting live streams several times due to proxy fault. It just broke randomly.

I've tried on 2 computers and met the same issue.

**Comment by rytsikau** [comment]
Starting from some version, the program checks for updates when it starts
Most likely you need to resolve the address raw.githubusercontent.com
Sorry :/

**Comment by Explorare** [comment]
Thanks for your reply. I've added it to proxy rules. The main issue that bothers me it that the program itself doesn't support proxy settings so I need to hijack the connection using some proxy tools. And there are more that 3 different proxy programs in the same layer to do similar thing and they just conflicts with each other sometimes. The program works again after the new update, thanks. 🎉
