### ISSUE TITLE
Will it work for country-limited livestream videos?

### ISSUE THREAD

**Issue by zphyrwlf** [rytsikau/ee.Yrewind#20]
Can this download videos that are only viewable in certain countries?

**Comment by rytsikau** [comment]
Have no idea. If you give an example of live stream that shouldn't be available in my country (Belarus), I can check

**Comment by zphyrwlf** [comment]
Like this one. It's gonna stream later and I wanna be able to download it 

https://www.youtube.com/watch?v=fZiyZF2JBrY

**Comment by computerfreak105** [comment]
Location Japan, due in about 60 min, right?
Use VPN and it should work fine.

**Comment by rytsikau** [comment]
Yes, it doesn't seem to work directly.
computerfreak105, hello!

**Comment by computerfreak105** [comment]
@Yauheni Rytsikau, hello to you as well! I love, and most of all trust your program :-)

Ok, I was curious and had a test my self with the provided Japanese stream:
 https://www.youtube.com/watch?v=fZiyZF2JBrY

With VPN I can play the video in the browser. But downloading is not possible: Unable to verify the saved video file is correct.
I just get 0 kb files with date, time and the title.

Are there some unicode charakters which aren’t included yet? Or is it a time zone issue?
I think it might be something to look into.

**Comment by rytsikau** [comment]
Is VPN enabled for FFmpeg? It looks like Yrewind is accessing YouTube via VPN, and FFmpeg directly

**Comment by computerfreak105** [comment]
I think a full featured VPN client like Surfshark will enable VPn for the whole system?

**Comment by rytsikau** [comment]
Both Yrewind and FFmpeg use the default network connection. Therefore, the VPN adapter should be assigned as the default network connection. Or (second option), if a separate VPN connection is assigned to the yrewind.exe process, then the same connection must be assigned to ffmpeg.exe

**Comment by computerfreak105** [comment]
Thanks, this might be the solution. I have to look into this and play with things when I’ve got time to do it.

**Comment by rytsikau** [comment]
OK! I'll close this thread, but if something clears up with VPN, please continue here
