### ISSUE TITLE
Start arguments combination

### ISSUE THREAD

**Issue by naabtog** [rytsikau/ee.Yrewind#25]
I discovered your program just yesterday and I can't describe how useful it is. AFAIK nobody's ever done that before.
There's a two hour recurrent stream and I need only the last hour of it. Is it possible to do with:
```
yrewind -url='channelURL' -start=wait+60
```
I could use the exact start time but livestream is a thing that can be delayed.
`ffmpeg` is already in my `PATH`, so can I delete one from `yrewind` folder without specifying `-ffmpeg` parameter?

**Comment by rytsikau** [comment]
1) Possibly, but the `-start` parameter already has too many different spellings. Is it worth to complicate even more?
2) Added to to-do list
