### ISSUE TITLE
Sometimes stops for no reason

### ISSUE THREAD

**Issue by mortang2410** [rytsikau/ee.Yrewind#26]
The issue is as stated. I like to capture streams from the start, with duration set at 300 (to be sure). Sometimes I can capture the whole stream. But sometimes it stalls mid-stream (the time stops increasing) and I can't figure what went wrong. 

So:
- Is there a way to ensure it won't stop in the middle of the stream?
- Failing that, if yrewind does stop at some point, is there a command to make it continue from that point on?

**Comment by brolnickij** [comment]
https://github.com/Kethsar/ytarchive

**Comment by corona12341** [comment]
Right-click the mouse
