### ISSUE TITLE
I can't save the age-restrict stream 

### ISSUE THREAD

**Issue by TaeDDin** [rytsikau/ee.Yrewind#28]
If you try to save an age-restrict stream, it says "ERROR 9238: Cannot get live stream information" and cannot be saved. Cookies are also loaded, If you have an adult-certified account, I would like you to support the age-restrict stream.

**Comment by rytsikau** [comment]
Hi! If the stream requires authorization to view, check that you are logged into the YouTube in the browser that Yrewind uses (in Chrome, or Edge if Chrome is not installed)

**Comment by TaeDDin** [comment]
An adult-certified account is logged in on YouTube and Cookie is an adult-certified account, but the above error appears.

**Comment by TaeDDin** [comment]
An adult-certified account is logged in on YouTube and Cookie is an adult-certified account, but the above error appears.

**Comment by TaeDDin** [comment]
An adult-certified account is logged in on YouTube and Cookie is an adult-certified account, but the above error appears. Please answer about my question.

**Comment by rytsikau** [comment]
Can you give an example url with this error?

**Comment by TaeDDin** [comment]
https://www.youtube.com/watch?v=10Zns5oOd-M
It's not a live streaming that I did before, but I can't do this after trying it. It seems that all age-certified live streaming are not available.

This is the syntax used. 
yrewind -url=https://www.youtube.com/watch?v=10Zns5oOd-M -cookie="cookies.txt" -start=wait -ffmpeg="C:\" -output=.mp4
cookies.txt is the txt obtained using the chromium extension program (Get cookies.txt).

**Comment by rytsikau** [comment]
Thanks, get the same error. In the next release will try to fix
