### ISSUE TITLE
How to save stream in mp4-H264 (no VP9)

### ISSUE THREAD

**Issue by btom1970** [rytsikau/ee.Yrewind#32]
I have some problems with VP9 codec. Some video editor can't handle it. 

My solution:
First, I download the stream in TS:
yrewind -url="--- LINK ---" -start=20220403:0800 -duration=120 -output=.ts

Than I fast-convert it to MP4: (this conversion really fast, no re-encoding)
ffmpeg -i FILENAME.ts -vcodec copy -acodec copy FILENAME.mp4

Result: no VP9 - simple mp4, what any video editor can handle

**Comment by btom1970** [comment]
Hi @rytsikau!
When I download as TS, some cases blank black screen in the video. Only sound, but file size is correct (big).
Why?

**Comment by rytsikau** [comment]
Hi! Firstly, try other builds of ffmpeg. Also the reason may be in the player...
