### ISSUE TITLE
error code 4911

### ISSUE THREAD

**Issue by corona12341** [rytsikau/ee.Yrewind#35]
On April 13, 2022, error code 9411 appears and is not working
The sentence may be awkward using a translato
![error](https://user-images.githubusercontent.com/103578671/163235910-ffff3df0-16ae-4a37-bc3c-7eacee0a7389.png)
r

**Comment by grichecth** [comment]
I'm not the dev but it looks to me you don't have a space before -start and it's running on into the URL. It would have given you an error but the 's around the URL cause it to not give the error.

For example:

You have:
yrewind -url='https://www.youtube.com/watch?v=NqxxC_n2S9Y'-start=-3 -duration=3 -output=.mp4

Should be:
yrewind -url='https://www.youtube.com/watch?v=NqxxC_n2S9Y' -start=-3 -duration=3 -output=.mp4
or
yrewind -u=https://www.youtube.com/watch?v=NqxxC_n2S9Y -s=-3 -d=3 -o=.mp4

Hope that helps!

**Comment by corona12341** [comment]
> 저는 개발자는 아니지만 -start 앞에 공백이 없고 URL에서 실행되고 있는 것 같습니다. 오류가 발생했지만 URL 주변의 's로 인해 오류가 발생하지 않습니다.
> 
> 예를 들어:
> 
> 당신은 가지고 있습니다: yrewind -url=' https://www.youtube.com/watch?v=NqxxC_n2S9Y'-start=-3 -duration=3 -output=.mp4
> 
> yrewind -url=' https://www.youtube.com/watch?v=NqxxC_n2S9Y ' -start=-3 -duration=3 -output=.mp4 또는 yrewind -u= [https://www.youtube .com/watch?v=NqxxC_n2S9Y](https://www.youtube.com/watch?v=NqxxC_n2S9Y) -s=-3 -d=3 -o=.mp4
> 
> 도움이 되기를 바랍니다!

Thank you. It's solved However, the download speed has slowed down, but do you know what is affected by this?

**Comment by rytsikau** [comment]
Hello! This stream is not active at this moment, it's a normal recorded video now. And Yrewind is focused only on ongoing streams, because for regular videos there is, for example, youtube-dl

**Comment by corona12341** [comment]
thanks friends! It's a really good program
