### ISSUE TITLE
Some links do not work 

### ISSUE THREAD

**Issue by corona12341** [rytsikau/ee.Yrewind#39]
yrewind -url= 'https://www.youtube.com/watch?v=KLJHprdBOww' -start=beginning -duration=60 -output=.mp4

Some links do not work
I just replaced the link, but there's something working, so I don't think it's my fault
![image](https://user-images.githubusercontent.com/103578671/165020691-f69bbd74-1119-4285-a698-546815d33249.png)

**Comment by rytsikau** [comment]
Next time try adding '-log=test200611', maybe it will help figure out what the error is

**Comment by rytsikau** [comment]
(but log files contains user IP, so maybe don't publish them)
