### ISSUE TITLE
The program doesn't work (for me)

### ISSUE THREAD

**Issue by 328791** [rytsikau/ee.Yrewind#4]
Hello,
I have tried your program with the sample URL in the run.bat file and also with other URLs on Windows 10. A few times it worked. But mostly I get the following error message:

version 21.011:
getting live stream data...
--> ERROR  9211: The specified URL does not exist (date and time)

version 20.124:
getting info about live stream...
--> ERROR 9254: Cannot extract live stream data (date and time)

Can you help me please?

I wish you a healthy and happy new year!

**Comment by rytsikau** [comment]
Hello! Have you tried version 20.123? Maybe it will work

**Comment by rytsikau** [comment]
Hi! Try the new version. If it still doesn't work, please write here

**Comment by 328791** [comment]
Hello,
with version 20.123 I get a similar error message as with version 20.124.

version 20.123:
      waiting for live stream data...
--> ERROR 9211: Cannot get live stream info (date and time)

But version 21.012 works fine!

Thanks a lot for this!
