### ISSUE TITLE
Feature Request: sub minute recordings

### ISSUE THREAD

**Issue by Domi207** [rytsikau/ee.Yrewind#41]
I think it would be useful to save clips that are shorter than one minute

**Comment by rytsikau** [comment]
Please check new version

**Comment by borisholowka** [comment]
Same Issue
![stream](https://user-images.githubusercontent.com/86146555/169785570-21a48adb-45ad-44ac-8cfe-d9da35da72fa.png)

**Comment by rytsikau** [comment]
It seems, this stream ended and been deleted. Next time try adding '-log=test200611', maybe it will help understand what is wrong

**Comment by rytsikau** [comment]
(perhaps they shouldn't be posted bcz contain user IP)
