### ISSUE TITLE
Stream title containing & or " produces error 9411 - ERROR 9411: Output file not created

### ISSUE THREAD

**Issue by ststoshev** [rytsikau/ee.Yrewind#42]
Hi, when I try to download from streams where the title contains symbols like & and ", the ERROR 9411: Output file not created
is displayed. When channel owner renamed the stream title without the & and ", it works. I suspect that ffmpeg doesn't like these characters, or they are not parsed correctly to ffmpeg somehow, so the error is returned.
Is there a way to make a fix in the Prepare code to avoid by deletion or substitution such incompatible characters?
Many thanks,
Steve.

**Comment by ststoshev** [comment]
Here is an example
getting live stream info...
    stream title        Auch bei "Lady Gaga" ist der Ausflug nicht mehr weit!
    resolutions         1080,720,480,360,240,144
    output file         UpIjd-yfdpI_20220529-094504_002m_0720p.mp4
--> ERROR 9411: Output file not created (30-May-22 12:58:05 AM)

**Comment by rytsikau** [comment]
Thank you! The problem here is the Unicode characters that FFmpeg cannot add to the file as metadata. I'll try to release fixed version as soon as possible

**Comment by rytsikau** [comment]
(although in this case it's really a matter of quotes)

**Comment by rytsikau** [comment]
Hello, the updated version shouldn't have this error. If have, please reopen this thread
