### ISSUE TITLE
Issues with channel URL

### ISSUE THREAD

**Issue by Kravatie** [rytsikau/ee.Yrewind#47]
Trying to set it up for this youtuber https://www.youtube.com/c/ginger

but it is saying the url is empty when it has the url in

![image](https://user-images.githubusercontent.com/109267988/179298370-7f9728af-24f7-4e96-978f-36c7f9ec6a78.png)

Doesn't seem to be anything in logs

**Comment by nvrskRU** [comment]
according to screenshot, you are trying to record not from **youtube.com/c/ginger** channel but from **youtube.com/user/copperhub** channel which does not exists.

**Comment by Kravatie** [comment]
It's a weird one because on youtube /c/ginger links to his channel name 

but i know youtube did something where they changed his channel name
