### ISSUE TITLE
System.ArgumentOutOfRangeException during usage

### ISSUE THREAD

**Issue by archfan7411** [rytsikau/ee.Yrewind#49]
I have a program which runs yrewind under the hood to automate collection of clips for a YouTube channel from their own livestreams. Sometimes this means the program is running multiple yrewind instances at once, in case that's important.

After the below error was shown, the program displayed a timer counting down. I ^C'd it shortly thereafter.

```
Unhandled Exception: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at yrewind.Program.CountdownTimer(Double seconds)
   at yrewind.Program.Main()
```

**Comment by rytsikau** [comment]
This is a bug, thanks. Looks like you resized the console when the countdown was showing. This caused the counter position to change and then an exception

**Comment by archfan7411** [comment]
We've had this error occur with seemingly increasing frequency now - and haven't been resizing the console (nor were we to begin with), in case that rules out some causes.

No rush of course, thanks for making this tool!

**Comment by rytsikau** [comment]
If the error will be again, please re-open thread
