### ISSUE TITLE
ERROR 9411: Cannot process live stream with FFmpeg library

### ISSUE THREAD

**Issue by FrantisekHrdina** [rytsikau/ee.Yrewind#5]
Hi, I am trying to download a part of one live stream, but I am getting this error message

ERROR 9411: Cannot process live stream with FFmpeg library

I am running that like this:
yrewind -url='https://www.youtube.com/watch?v=DSeT2ngZFtI' -start:20200108:1500 -duration=1 -resolution=9999 -pathsave='D:\downloads\'

Am I using it wrong?
Than you for help

**Comment by rytsikau** [comment]
Hi! Check the '-start:20200108:1500' parameter. Probably should be '-start=20210108:1500'

**Comment by FrantisekHrdina** [comment]
> Hi! Check the '-start:20200108:1500' parameter. Probably should be '-start=20210108:1500'

Hey, thank you, you are right. I am still living in 2020, my bad.
