### ISSUE TITLE
How can I download a finished livestream with -b or -c

### ISSUE THREAD

**Issue by btom1970** [rytsikau/ee.Yrewind#58]
I don't found about -b -c option nothing in help...

**Comment by btom1970** [comment]
I found -browser or -cookies. But these are for restricted streams.
How can I download a finished stream?

**Comment by rytsikau** [comment]
-b and -c are just synonyms for -browser and -cookies

**Comment by rytsikau** [comment]
Recently finished livestream can be downloaded within ~6 hours after it finished. After that, if the author has saved the stream to his channel, it can be downloaded as a regular video (with youtube-dl, etc.)
If the author has not saved, then the stream cannot be downloaded at all.

**Comment by btom1970** [comment]
The live stream ended around 09:00-10:00 today. I tryed to download at 13:00 today and get this message.![2023-04-12 19_27_27-ee Yrewind](https://user-images.githubusercontent.com/86095054/231538695-f8ff9c79-6a52-46ec-94f4-387680b4717c.jpg)

**Comment by rytsikau** [comment]
So did you tried -b/-c?

**Comment by rytsikau** [comment]
This is not necessarily a bug, perhaps the author restrict access to the stream after it ended. Or (most likely) just deleted it, in this case -b and -c couldn't help

**Comment by btom1970** [comment]
> So did you tried -b/-c?

No. I don't tried it. How can I try? Cookies, browser?

**Comment by rytsikau** [comment]
In general, for restricted streams that require a login, -b can be used instead of -c. This is if you specify the browser in which you are logged into Youtube.

**Comment by rytsikau** [comment]
But in this particular case it would not help, here the stream is simply deleted

**Comment by btom1970** [comment]
I download from this stream many, no login required. I think it was deleted, as You said. Thx for the answers!
