### ISSUE TITLE
Support for longer durations please?

### ISSUE THREAD

**Issue by SergioLuisBerto** [rytsikau/ee.Yrewind#8]
First i want to thank you for your work on this, this works really well overall.

With that said, why the limit on duration be 90 minutes? There's lots of streams that goes for hours and hours.
There should be possible to set a longer duration. I personally am frequently downloading streams that are quite long (sometimes even 3 hours long or more) which are from free studying events that are often not available to watch later, so it's useful for me to be able to just leave it downloading while i'm working on something else and then when i get time i watch it all.

**Comment by rytsikau** [comment]
It's just for reliability. If you record in single file, in case of any problems (network error, frozen computer, etc.), you will get one large incomplete (or even damaged) video. Therefore, a batch file with repeated lines like "yrewind -url=9Auq9mYxFEE -duration=60" looks more reliable than a single line like "yrewind -url=9Auq9mYxFEE -duration=600".

**Comment by SergioLuisBerto** [comment]
Hm, I understand your reasoning. But i think that should be up to the user to decide. You should just leave a warning, but still allow it, in my opinion. Also, theres the `-vformat=ts` that should deal with network errors atleast right?

Now, about your solution, i have a question:
For example, if a stream is currently 30 minutes long, but it will have a total duration of 3 hours. If, @30minutes i run a batch with 2 commands, one with `-start=beginning -duration=90` and another one with `-start=+90 -duration=90`, will the second one work normally and only start recording once the stream reaches that long? If yes then i guess thats an OK workaround. If it requires for the stream to be atleast 90minutes long for the 2nd command to work then it wont be a proper workaround.

I know i could just test that myself (and i will), but i cant do that right now, and even then, i guess it will be useful for someone in the future to have this comment here. The documentation is not clear about that so thats why i'm asking.

Anyway, thanks for the response.

**Comment by rytsikau** [comment]
"But i think that should be up to the user to decide. You should just leave a warning, but still allow it, in my opinion"
- There is nothing to object. Honestly, this is what I thought when I wrote answer to you. In the next release will fix this bug )

**Comment by rytsikau** [comment]
In batch file, in this case, the file should contain two lines:
"-start=beginning -duration=90"
"-duration=90"
The first line loads the stream from the beginning and then continues in real time, the second continue recording in real time.

**Comment by rytsikau** [comment]
Reference point of "-start" is a time when program starts, not the beginning of the stream

**Comment by SergioLuisBerto** [comment]
Oh i see what you mean. I thought with the `-start=+90` it would start recording from the 1:30:00 mark.
Hm, then that wouldnt work as a workaround for the situation i described.
It's OK though, I will just wait for when you drop the next version without duration limits then. Thanks!

**Comment by rytsikau** [comment]
Maximum duration increased to 300 minutes. Further increase is associated with certain nuances. Nothing complicated, but it doesn't seem like a priority )
